import test from 'node:test';
import assert from 'node:assert/strict';
import {canonicalHash,chooseProtectedCleanup,localRestorePatch,assertBudget,TOTAL_MS,CLEANUP_MS,pendingDeploymentIds,jobBody} from '../checks/sandbox-build.check.mjs';
test('import is inert and does not require native authorization',()=>{assert.equal(TOTAL_MS,120000);assert.equal(CLEANUP_MS,35000);});
test('selective protection cleanup preserves baseline and foreign additions',()=>{assert.deepEqual(chooseProtectedCleanup(['community:original'],['community:test'],['community:original','community:test','core:new-foreign']),['community:original','core:new-foreign']);});
test('cleanup never removes a baseline protection even if mistakenly listed as added',()=>{assert.deepEqual(chooseProtectedCleanup(['core:search'],['core:search'],['core:search']),['core:search']);});
test('local cleanup restores only its matching postimage',()=>{const before={recoveryReason:'original',deviceProfileId:null},post={recoveryReason:'test',deviceProfileId:null};assert.deepEqual(localRestorePatch(before,post,{recoveryReason:'test',deviceProfileId:'user-new'}),{patch:{recoveryReason:'original'},conflicts:[]});assert.deepEqual(localRestorePatch(before,post,{recoveryReason:'user-error'}),{patch:{},conflicts:['recoveryReason']});});
test('budget prevents new mutations inside cleanup reserve',()=>{assert.equal(assertBudget(120000,35000,80000),40000);assert.throws(()=>assertBudget(120000,35000,85000));assert.throws(()=>assertBudget(120000,0,120000));});
test('same profile count does not imply preserved definitions',()=>{const a=[{id:'macbook',tags:['macbook']}],b=[{id:'macbook',tags:['zenbook']}];assert.notEqual(canonicalHash(a),canonicalHash(b));});
test('canonical profile content tolerates object key order but detects membership order',()=>{assert.equal(canonicalHash([{id:'p',applyAtStart:true}]),canonicalHash([{applyAtStart:true,id:'p'}]));assert.notEqual(canonicalHash(['a','b']),canonicalHash(['b','a']));});

test('pending async deployment is detected before another operation starts',()=>{assert.deepEqual(pendingDeploymentIds({'aigility-manager-deploy:old':{status:'pending'},'aigility-manager-deploy:done':{status:'complete'},foreign:{status:'pending'}}),['aigility-manager-deploy:old']);});
test('actual native job wrapper persists success and failure phases without another execution',async()=>{const FakeAsync=Object.getPrototypeOf(async function(){}).constructor;const globals={};const body=jobBody('aigility-manager-deploy:test','protect','value={ok:true}',Date.now()+10000);const exec=new FakeAsync('globalThis','let value;'+body+'return value;');assert.deepEqual(await exec(globals),{ok:true});assert.equal(globals['aigility-manager-deploy:test'].status,'complete');const bad=new FakeAsync('globalThis','let value;'+jobBody('aigility-manager-deploy:bad','protect',"throw Error('disk failure')",Date.now()+10000));await assert.rejects(()=>bad(globals),/disk failure/);assert.equal(globals['aigility-manager-deploy:bad'].status,'failed');});
