import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {cleanupOwnedFixtureFiles,cleanupOwnedManifest} from '../checks/profile-file-cleanup-v013.mjs';
import {fixtureFiles,FIXTURE_IDS} from '../checks/profile-fixture-plan.mjs';
const digest=text=>createHash('sha256').update(text).digest('hex');
function fixture(){
 const files=new Map(),dirs=new Set(),calls=[];
 const owned=FIXTURE_IDS.map(id=>{const directory='.obsidian/plugins/'+id,contents=fixtureFiles(id);dirs.add(directory);for(const [n,v]of Object.entries(contents))files.set(directory+'/'+n,v);return {id,directory,hashes:Object.fromEntries(Object.entries(contents).map(([n,v])=>[n,digest(v)]))};});
 files.set('.obsidian/plugins/foreign/data.json','foreign');dirs.add('.obsidian/plugins/foreign');
 const adapter={list:async dir=>({files:[...files.keys()].filter(p=>p.startsWith(dir+'/')&&!p.slice(dir.length+1).includes('/')),folders:[...dirs].filter(p=>p.startsWith(dir+'/'))}),read:async p=>{assert.ok(files.has(p));return files.get(p);},exists:async p=>files.has(p)||dirs.has(p),remove:async p=>{assert.ok(files.has(p),'remove is FILE-only');calls.push(['file',p]);files.delete(p);},rmdir:async(p,recursive)=>{assert.equal(recursive,false);assert.ok(![...files.keys(),...dirs].some(k=>k.startsWith(p+'/')),'nonempty directory refused');calls.push(['dir',p]);dirs.delete(p);}};
 return {files,dirs,owned,adapter,calls};
}
const opts={gate:()=>{},digest};
test('exact two fixture folders removed nonrecursively while foreign file survives',async()=>{const f=fixture();const result=await cleanupOwnedFixtureFiles(f.adapter,f.owned,opts);assert.equal(result.removed.length,8);assert.equal(f.calls.filter(x=>x[0]==='dir').length,2);assert.deepEqual([...f.files],[['.obsidian/plugins/foreign/data.json','foreign']]);assert.equal(f.dirs.size,1);});
test('extra file or subfolder refuses namespace before any deletion',async()=>{for(const kind of ['file','dir']){const f=fixture(),root=f.owned[0].directory;if(kind==='file')f.files.set(root+'/manual.txt','manual');else f.dirs.add(root+'/manual');await assert.rejects(()=>cleanupOwnedFixtureFiles(f.adapter,f.owned,opts),/Unexpected/);assert.equal(f.calls.length,0);}});
test('manual file edit in planned await is preserved before file deletion',async()=>{const f=fixture(),file=f.owned[0].directory+'/manifest.json';await assert.rejects(()=>cleanupOwnedFixtureFiles(f.adapter,f.owned,{...opts,onStep:async s=>{if(s.status==='planned'&&s.path===file)f.files.set(file,'manual');}}),/postimage changed/);assert.equal(f.files.get(file),'manual');assert.equal(f.calls.length,0);});
test('late foreign file before rmdir survives with no recursive deletion',async()=>{const f=fixture(),root=f.owned[0].directory;await assert.rejects(()=>cleanupOwnedFixtureFiles(f.adapter,f.owned,{...opts,onStep:async s=>{if(s.phase==='remove-empty-fixture-directory'&&s.status==='planned')f.files.set(root+'/late.txt','late');}}),/Unexpected/);assert.equal(f.files.get(root+'/late.txt'),'late');assert.equal(f.calls.some(x=>x[0]==='dir'),false);});
test('expiry during held read prevents every subsequent remove',async()=>{const f=fixture();let expired=false;const read=f.adapter.read;f.adapter.read=async p=>{const text=await read(p);await Promise.resolve();expired=true;return text;};await assert.rejects(()=>cleanupOwnedFixtureFiles(f.adapter,f.owned,{digest,gate:()=>{if(expired)throw Error('deadline');}}),/deadline/);assert.equal(f.calls.length,0);});
test('partial removal followed by drift preserves remaining owned and foreign files',async()=>{const f=fixture(),root=f.owned[0].directory;await assert.rejects(()=>cleanupOwnedFixtureFiles(f.adapter,f.owned,{...opts,onStep:async s=>{if(s.status==='settled'&&s.path===root+'/manifest.json')f.files.set(root+'/main.js','manual');}}),/postimage changed/);assert.equal(f.calls.length,1);assert.equal(f.files.get(root+'/main.js'),'manual');assert.equal(f.files.has(root+'/data.json'),true);assert.equal(f.files.has('.obsidian/plugins/foreign/data.json'),true);});
test('malformed or duplicate namespace rejected before adapter calls',async()=>{for(const mutate of [o=>o[0].id='../foreign',o=>o[0].directory+='/',o=>o[1]=o[0],o=>delete o[0].hashes['custom.txt']]){const f=fixture();mutate(f.owned);await assert.rejects(()=>cleanupOwnedFixtureFiles(f.adapter,f.owned,opts),/Invalid|Exact/);assert.equal(f.calls.length,0);}});
test('manifest slot removal requires exact object identity and both native and loaded OFF',()=>{const id=FIXTURE_IDS[0],manifest={id},app={plugins:{manifests:{[id]:manifest},enabledPlugins:new Set(),plugins:{}}};app.plugins.manifests[id]={id};assert.throws(()=>cleanupOwnedManifest(app,id,manifest,opts),/replaced/);app.plugins.manifests[id]=manifest;app.plugins.enabledPlugins.add(id);assert.throws(()=>cleanupOwnedManifest(app,id,manifest,opts),/still/);app.plugins.enabledPlugins.clear();app.plugins.plugins[id]={_loaded:true};assert.throws(()=>cleanupOwnedManifest(app,id,manifest,opts),/still/);delete app.plugins.plugins[id];assert.deepEqual(cleanupOwnedManifest(app,id,manifest,opts),{id,removed:true});assert.equal(app.plugins.manifests[id],undefined);});
test('serialized helpers compile without module closure dependencies',()=>{for(const fn of [cleanupOwnedFixtureFiles,cleanupOwnedManifest])assert.doesNotThrow(()=>new Function('return ('+fn.toString()+')'));});
