import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {importModule} from '../test.config.mjs';
import {runProfileController,profileControllerBody,profileHelpers} from '../checks/profile-controller-v013.mjs';
import {nativeProfileReadback} from '../checks/sandbox-profiles-v013.check.mjs';
const {ManagerRuntime}=await importModule('src/integrated/runtime.ts');
const MANAGER='aigility-plugin-manager';
function host({existing=false,expireRead=false}={}){
 const storage=new Map();globalThis.localStorage={getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k)};
 const globals={},files=new Map(),dirs=new Set(),calls=[];
 const state={schemaVersion:1,records:{'community:foreign':{ref:{kind:'community',id:'foreign'},name:'Foreign',version:'1.0.0',tags:[],group:'',desired:true,metadata:{}},'core:core':{ref:{kind:'core',id:'core'},name:'Core',version:'1.0.0',tags:[],group:'',desired:true,metadata:{}}},tags:[],groups:[],deviceProfiles:[],fixtureProfiles:[],deferred:[],profileBackups:[],protected:['community:'+MANAGER],githubSources:{},settings:{staggerMs:0,automaticUpdates:false},legacyBpm:{}};
 const manager={_loaded:true,manifest:{id:MANAGER,version:'0.1.3',dir:'.obsidian/plugins/'+MANAGER},logger:{error(){},warn(){},info(){},debug(){}}};
 const plugins={manifests:{[MANAGER]:manager.manifest,foreign:{id:'foreign',version:'1.0.0',name:'Foreign'}},plugins:{[MANAGER]:manager,foreign:{_loaded:true}},enabledPlugins:new Set([MANAGER,'foreign']),isEnabled:()=>true,getPlugin(id){return this.plugins[id];},async loadManifest(dir){calls.push(['manifest',dir]);const m=JSON.parse(files.get(dir+'/manifest.json'));m.dir=dir;this.manifests[m.id]=m;},async enablePluginAndSave(id){assert.match(id,/^aigility-manager-fixture-[ab]$/);calls.push(['enable',id]);this.enabledPlugins.add(id);this.plugins[id]={_loaded:true,manifest:this.manifests[id]};globals['aigility-host-count:'+id]=(globals['aigility-host-count:'+id]??0)+1;},async disablePluginAndSave(id){assert.match(id,/^aigility-manager-fixture-[ab]$/);calls.push(['disable',id]);this.enabledPlugins.delete(id);delete this.plugins[id];}};
 const core={enabled:true,instance:{_loaded:true,manifest:{id:'core',name:'Core'}},enable(){throw Error('Foreign core mutation forbidden');},disable(){throw Error('Foreign core mutation forbidden');}};
 const adapter={getBasePath:()=> '/Users/eme/Obsidian/Sandbox',exists:async p=>files.has(p)||dirs.has(p),read:async p=>{if(expireRead){expireRead=false;await new Promise(r=>setTimeout(r,20));}assert.ok(files.has(p));return files.get(p);},write:async(p,v)=>files.set(p,v),mkdir:async p=>{assert.equal(dirs.has(p),false);dirs.add(p);},list:async dir=>({files:[...files.keys()].filter(p=>p.startsWith(dir+'/')&&!p.slice(dir.length+1).includes('/')),folders:[...dirs].filter(p=>p.startsWith(dir+'/'))}),remove:async p=>{assert.ok(files.has(p));files.delete(p);},rmdir:async(p,recursive)=>{assert.equal(recursive,false);assert.equal([...files.keys(),...dirs].some(k=>k.startsWith(p+'/')),false);dirs.delete(p);}};
 const app={appId:'d137282e82167d84',manifest:{version:'1.14.3'},plugins,internalPlugins:{plugins:{core},getPluginById(id){return this.plugins[id];}},vault:{configDir:'.obsidian',adapter,getName:()=> 'Sandbox'},workspace:{activeLeaf:{id:'leaf'},containerEl:{ownerDocument:globalThis.document},iterateAllLeaves(fn){fn(this.activeLeaf);}},setting:{modalEl:{isConnected:false},doc:{},activeTab:null,lastTabId:'voiceink-companion'}};
 files.set(manager.manifest.dir+'/data.json',JSON.stringify(state));const rt=new ManagerRuntime(app,manager,state);manager.runtime=rt;rt.pause('Recovery must remain paused');
 if(existing)dirs.add('.obsidian/plugins/aigility-manager-fixture-a');
 return {app,globals,files,dirs,calls,manager,rt};
}
const budget=()=>({actionDeadline:Date.now()+5000,cleanupDeadline:Date.now()+10000});
test('whole controller runs actual runtime cases and restores state/local/native/manifest/files without foreign operations',async()=>{
 const f=host(),before=JSON.stringify(f.rt.state),local=JSON.stringify(f.rt.local),source=f.manager.runtime;try{
  const result=await runProfileController(f.app,f.globals,'aigility-manager-profile:happy',budget(),profileHelpers);
  assert.equal(result.status,'complete',JSON.stringify(result));assert.deepEqual(result.result.counterDeltas,{a:3,b:3});
  assert.equal(JSON.stringify(f.rt.state),before);assert.equal(JSON.stringify(f.rt.local),local);assert.equal(f.rt.profileUndo,undefined);
  assert.deepEqual(Object.keys(f.app.plugins.manifests).sort(),['aigility-plugin-manager','foreign']);assert.equal(f.dirs.size,0);assert.equal(f.files.size,2);assert.equal(f.manager.runtime,source);assert.equal(result.postimages.length,11);
 }finally{f.rt.dispose();}
});
test('existing namespace refuses before any fixture or foreign mutation',async()=>{const f=host({existing:true});try{const r=await runProfileController(f.app,f.globals,'aigility-manager-profile:existing',budget(),profileHelpers);assert.equal(r.status,'failed');assert.match(r.error,/namespace already exists/);assert.equal(f.calls.length,0);assert.equal(f.dirs.size,1);}finally{f.rt.dispose();}});
test('expiry during awaited initial read stops fixture setup and preserves foreign state',async()=>{const f=host({expireRead:true});try{const r=await runProfileController(f.app,f.globals,'aigility-manager-profile:expiry',{actionDeadline:Date.now()+5,cleanupDeadline:Date.now()+2000},profileHelpers);assert.equal(r.status,'failed');assert.match(r.error,/deadline/);assert.equal(f.calls.length,0);assert.equal(f.dirs.size,0);assert.equal(f.app.plugins.enabledPlugins.has('foreign'),true);}finally{f.rt.dispose();}});
test('serialized whole controller executes with injected native-shaped app, not merely case body',async()=>{const f=host();try{const b=budget(),body=profileControllerBody('aigility-manager-profile:serialized',b.actionDeadline,b.cleanupDeadline),fn=new Function('app','globalThis','require','return ('+body+');')(f.app,f.globals,createRequire(import.meta.url));const r=await fn();assert.equal(r.status,'complete',JSON.stringify(r));assert.equal(f.dirs.size,0);assert.equal(f.calls.filter(x=>x[0]==='manifest').length,2);}finally{f.rt.dispose();}});

import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
test('actual serialized durable phase writer leaves a parseable owned receipt and preserves lease metadata',async()=>{
 const f=host(),dir=await mkdtemp(path.join(tmpdir(),'aigility-profile-receipt-')),receipt=path.join(dir,'own.json'),key='aigility-manager-profile:durable';
 try{const b=budget(),metadata={key,status:'dispatch-prepared',leaseId:'offline-test',ackUTC:'offline',startBy:1,actionDeadline:b.actionDeadline,deadline:b.cleanupDeadline,nativeToken:'a'.repeat(32),nativeIdentity:null},raw=JSON.stringify(metadata,null,2)+'\n';await writeFile(receipt,raw);const fn=new Function('app','globalThis','require','return ('+profileControllerBody(key,b.actionDeadline,b.cleanupDeadline,receipt,false,{receiptRaw:raw,receiptMetadata:metadata})+');')(f.app,f.globals,createRequire(import.meta.url));const result=await fn();assert.equal(result.status,'complete',JSON.stringify(result));const finalRaw=await readFile(receipt,'utf8'),saved=JSON.parse(finalRaw);assert.equal(saved.status,'complete');assert.equal(saved.leaseId,'offline-test');assert.equal(saved.key,key);assert.ok(saved.journal.length>16);assert.equal(finalRaw.endsWith('\n'),true);}finally{f.rt.dispose();await rm(dir,{recursive:true,force:true});}
});

test('later manual owned tag edit is preserved and prevents fixture file deletion',async()=>{const f=host(),h={...profileHelpers,runOwnedProfileCases:async(...args)=>{const result=await profileHelpers.runOwnedProfileCases(...args);await f.rt.enqueue('manual-create-tag',async tx=>{const state=await tx.refresh();state.tags.push({id:'manual-user-tag',name:'Manual tag'});await tx.save();});await f.rt.setTags({kind:'community',id:'aigility-manager-fixture-a'},['manual-user-tag']);return result;}};try{const r=await runProfileController(f.app,f.globals,'aigility-manager-profile:manual-tag',budget(),h);assert.equal(r.status,'failed');assert.equal(r.restoration.state,false);assert.equal(r.restoration.files,false);assert.deepEqual(f.rt.state.records['community:aigility-manager-fixture-a'].tags,['manual-user-tag']);assert.equal(f.files.has('.obsidian/plugins/aigility-manager-fixture-a/data.json'),true);assert.deepEqual(f.rt.state.protected,['community:'+MANAGER]);assert.equal(f.app.plugins.enabledPlugins.has('foreign'),true);}finally{f.rt.dispose();}});
test('later manual fixture file edit survives cleanup and is reported, without foreign rollback',async()=>{const f=host(),h={...profileHelpers,runOwnedProfileCases:async(...args)=>{const result=await profileHelpers.runOwnedProfileCases(...args);f.files.set('.obsidian/plugins/aigility-manager-fixture-a/custom.txt','manual file');return result;}};try{const r=await runProfileController(f.app,f.globals,'aigility-manager-profile:manual-file',budget(),h);assert.equal(r.status,'failed');assert.equal(r.restoration.files,false);assert.equal(f.files.get('.obsidian/plugins/aigility-manager-fixture-a/custom.txt'),'manual file');assert.equal(f.app.plugins.enabledPlugins.has('foreign'),true);assert.ok(f.app.plugins.manifests['aigility-manager-fixture-a']);}finally{f.rt.dispose();}});
test('durable baseline and each case intent precede native mutation, and every cleanup delete has persisted intent',async()=>{const f=host(),snapshots=[],h={...profileHelpers,persistJob:j=>snapshots.push(structuredClone(j))};const enable=f.app.plugins.enablePluginAndSave;f.app.plugins.enablePluginAndSave=async function(id){const saved=snapshots.at(-1);assert.ok(saved.baseline.stateHash);assert.ok(saved.casePending);return enable.call(this,id);};const remove=f.app.vault.adapter.remove;f.app.vault.adapter.remove=async p=>{const saved=snapshots.at(-1);assert.ok(saved.journal.some(s=>s.path===p&&s.status==='planned'&&s.phase==='remove-fixture-file'));return remove(p);};try{const r=await runProfileController(f.app,f.globals,'aigility-manager-profile:persisted',budget(),h);assert.equal(r.status,'complete',JSON.stringify(r));assert.equal(snapshots.at(-1).status,'complete');assert.equal(snapshots.at(-1).postimages.length,11);}finally{f.rt.dispose();}});
test('incomplete fixture write reports exact residue and removes only temporary foreign protections',async()=>{const f=host(),write=f.app.vault.adapter.write;f.app.vault.adapter.write=async(p,v)=>{if(p.endsWith('/main.js')&&p.includes('fixture-a'))throw Error('Injected write failure');return write(p,v);};try{const r=await runProfileController(f.app,f.globals,'aigility-manager-profile:write-failure',budget(),profileHelpers);assert.equal(r.status,'failed');assert.match(r.error,/write failure/);assert.deepEqual(f.rt.state.protected,['community:'+MANAGER]);assert.equal(f.calls.length,0);assert.equal(f.files.has('.obsidian/plugins/aigility-manager-fixture-a/manifest.json'),true);assert.equal(r.restoration.files,false);}finally{f.rt.dispose();}});
test('invalid deadlines refuse before creating job or mutation',async()=>{const f=host();try{await assert.rejects(runProfileController(f.app,f.globals,'aigility-manager-profile:invalid',{actionDeadline:NaN,cleanupDeadline:Infinity},profileHelpers),/Finite ordered/);assert.deepEqual(f.globals,{});assert.equal(f.calls.length,0);}finally{f.rt.dispose();}});
test('native serialization resolves Electron remote inside injected host and pins primary window through awaits',async()=>{const f=host(),doc={documentURI:'offline://Sandbox'},requireNode=createRequire(import.meta.url),win={id:17,webContents:{id:19,getURL:()=> 'offline://Sandbox'}},baselineKey='aigility-manager-profile-baseline:offline',baselineToken='a'.repeat(32);f.app.workspace.containerEl.ownerDocument=doc;f.globals[baselineKey]={token:baselineToken,documentRef:doc,windowRef:win,webContentsRef:win.webContents};const nativeIdentity={windowId:17,webContentsId:19,documentURL:doc.documentURI,webContentsURL:win.webContents.getURL(),baselineKey,baselineToken};const injectedRequire=name=>name==='@electron/remote'?{getCurrentWindow:()=>win}:requireNode(name);try{const b=budget(),fn=new Function('app','globalThis','require','document','return ('+profileControllerBody('aigility-manager-profile:native-window',b.actionDeadline,b.cleanupDeadline,null,true,{nativeIdentity})+');')(f.app,f.globals,injectedRequire,doc),r=await fn();assert.equal(r.status,'complete',JSON.stringify(r));assert.equal(r.primaryWindowId,17);}finally{f.rt.dispose();}});

test('pending UI owner prevents a profile job before any native or file operation',async()=>{const f=host();f.globals['aigility-manager-ui:foreign-job']={status:'pending'};try{await assert.rejects(runProfileController(f.app,f.globals,'aigility-manager-profile:overlap',budget(),profileHelpers),/Manager job exists/);assert.equal(f.calls.length,0);assert.equal(f.dirs.size,0);}finally{f.rt.dispose();}});
test('independent readback checks actual whole runtime, local/native/core, workspace and namespaces',async()=>{const f=host(),key='aigility-manager-profile:readback';try{const r=await runProfileController(f.app,f.globals,key,budget(),{...profileHelpers,primaryWindowId:1});assert.equal(r.status,'complete');const read=await nativeProfileReadback(f.app,f.globals,key,f.app.workspace.containerEl.ownerDocument,()=>1,profileHelpers.digest);assert.equal(read.foreignCount,2);assert.equal(read.coreCount,1);assert.ok(read.namespaces.every(x=>!x.exists&&!x.manifest&&!x.native&&!x.loaded));f.rt.local.deviceProfileId='manual-choice';await assert.rejects(nativeProfileReadback(f.app,f.globals,key,f.app.workspace.containerEl.ownerDocument,()=>1,profileHelpers.digest),/readback mismatch/);assert.equal(f.rt.local.deviceProfileId,'manual-choice');}finally{f.rt.dispose();}});
test('independent readback refuses manager replacement after an awaited namespace read',async()=>{const f=host(),key='aigility-manager-profile:readback-drift';try{await runProfileController(f.app,f.globals,key,budget(),{...profileHelpers,primaryWindowId:1});const exists=f.app.vault.adapter.exists;f.app.vault.adapter.exists=async p=>{const result=await exists(p);f.app.plugins.plugins[MANAGER]={_loaded:true};return result;};await assert.rejects(nativeProfileReadback(f.app,f.globals,key,f.app.workspace.containerEl.ownerDocument,()=>1,profileHelpers.digest),/identity mismatch/);}finally{f.rt.dispose();}});
async function ownershipController({replaceReceipt=false,replaceWindow=false}={}){
 const f=host(),dir=await mkdtemp(path.join(tmpdir(),'aigility-strict-ownership-')),receipt=path.join(dir,'receipt.json'),key='aigility-manager-profile:strict',doc={documentURI:'offline://Sandbox'},win={id:1,webContents:{id:12,getURL:()=> 'offline://Sandbox'}},baselineKey='aigility-manager-profile-baseline:strict',baselineToken='a'.repeat(32);
 f.app.workspace.containerEl.ownerDocument=doc;f.globals[baselineKey]={token:baselineToken,documentRef:doc,windowRef:win,webContentsRef:win.webContents};
 const nativeIdentity={windowId:1,webContentsId:12,documentURL:doc.documentURI,webContentsURL:win.webContents.getURL(),baselineKey,baselineToken},b=budget(),metadata={key,leaseId:'strict-test',ackUTC:'offline',startBy:1,actionDeadline:b.actionDeadline,deadline:b.cleanupDeadline,nativeToken:'b'.repeat(32),nativeIdentity,status:'dispatch-prepared'},raw=JSON.stringify(metadata,null,2)+'\n';await writeFile(receipt,raw);
 const requireNode=createRequire(import.meta.url),realFs=requireNode('fs'),proxy=Object.create(realFs),original=f.rt.host.setEnabled,descriptor=Object.getOwnPropertyDescriptor(f.rt.host,'setEnabled'),foreign='foreign receipt replacement';let planned=false;
 proxy.writeSync=(fd,text,...args)=>{if(JSON.parse(text).wrapperIntent?.status==='planned'){planned=true;assert.equal(f.rt.host.setEnabled,original);assert.deepEqual(Object.getOwnPropertyDescriptor(f.rt.host,'setEnabled'),descriptor);assert.equal(f.globals[key].hostWrapperOwnership.originalHost,original);if(replaceReceipt){const replacement=receipt+'.replacement';realFs.writeFileSync(replacement,foreign);realFs.renameSync(replacement,receipt);}}return realFs.writeSync(fd,text,...args);};
 const injectedRequire=name=>name==='@electron/remote'?{getCurrentWindow:()=>replaceWindow?{...win,webContents:{...win.webContents}}:win}:name==='fs'?proxy:requireNode(name);
 const invoke=new Function('app','globalThis','require','document','return ('+profileControllerBody(key,b.actionDeadline,b.cleanupDeadline,receipt,true,{nativeIdentity,receiptMetadata:metadata,receiptRaw:raw})+');')(f.app,f.globals,injectedRequire,doc);
 try{
  if(replaceReceipt){await assert.rejects(invoke(),/Receipt expected bytes changed/);assert.equal(await readFile(receipt,'utf8'),foreign);assert.equal(f.calls.some(([kind])=>kind==='enable'||kind==='disable'),false);assert.deepEqual(Object.getOwnPropertyDescriptor(f.rt.host,'setEnabled'),descriptor);assert.equal(f.globals[key].status,'pending');assert.equal(planned,true);}
  else if(replaceWindow){await assert.rejects(invoke(),/references changed/);assert.equal(f.globals[key],undefined);assert.equal(f.dirs.size,0);assert.equal(await readFile(receipt,'utf8'),raw);}
  else{const r=await invoke();assert.equal(r.status,'complete',JSON.stringify(r));assert.equal(planned,true);assert.deepEqual(r.result.counterDeltas,{a:3,b:3});assert.deepEqual(Object.getOwnPropertyDescriptor(f.rt.host,'setEnabled'),descriptor);assert.equal(r.wrapperIntent.status,'restored');const final=JSON.parse(await readFile(receipt,'utf8'));assert.equal(final.nativeToken,metadata.nativeToken);assert.equal(final.deadline,metadata.deadline);assert.equal(final.status,'complete');}
 }finally{f.rt.dispose();await rm(dir,{recursive:true,force:true});}
}
test('ownership focal actual serialized controller persists wrapper intent before installation and restores native descriptor',()=>ownershipController());
test('ownership focal actual receipt replacement during wrapper intent preserves foreign receipt and prevents activation',()=>ownershipController({replaceReceipt:true}));
test('ownership focal actual serialized controller refuses replacement window before registering native job',()=>ownershipController({replaceWindow:true}));
