import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {mkdtempSync,readFileSync,writeFileSync,rmSync,renameSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {writeReceiptCAS,frozenNativeIdentity} from '../checks/profile-ownership-v013.mjs';
const metadata={key:'aigility-manager-profile:test',leaseId:'test',ackUTC:'2026-10-01T22:00:00Z',startBy:1,deadline:3,actionDeadline:2,nativeToken:'a'.repeat(32),nativeIdentity:{windowId:1}};
function receipt(fn){const dir=mkdtempSync(path.join(tmpdir(),'aigility-receipt-cas-')),file=path.join(dir,'receipt.json'),raw=JSON.stringify({...metadata,status:'pending'},null,2)+'\n';writeFileSync(file,raw);try{return fn({dir,file,raw});}finally{rmSync(dir,{recursive:true,force:true});}}
test('ownership focal receipt updates only complete immutable envelope and exact expected bytes',()=>receipt(({file,raw})=>{const next={...metadata,status:'complete'};const saved=writeReceiptCAS(fs,file,raw,metadata,next);assert.equal(readFileSync(file,'utf8'),saved);assert.equal(JSON.parse(saved).status,'complete');}));
test('ownership focal same-key receipt replacement is preserved byte for byte',()=>receipt(({file,raw})=>{const foreign=JSON.stringify({...metadata,status:'foreign',extra:'manual'});writeFileSync(file,foreign);assert.throws(()=>writeReceiptCAS(fs,file,raw,metadata,{...metadata,status:'complete'}),/expected bytes changed/);assert.equal(readFileSync(file,'utf8'),foreign);}));
test('ownership focal changed token lease deadline and target cannot overwrite receipt even with matching key',()=>receipt(({file,raw})=>{for(const field of ['nativeToken','leaseId','deadline','actionDeadline','nativeIdentity']){assert.throws(()=>writeReceiptCAS(fs,file,raw,metadata,{...metadata,[field]:'replacement'}),/immutable ownership changed/);assert.equal(readFileSync(file,'utf8'),raw);}}));
test('ownership focal summary publication requires explicit previous and new envelopes, never adopts current bytes',()=>receipt(({file,raw})=>{const nextMetadata={...metadata,key:'aigility-manager-profile:next',leaseId:'next',nativeToken:'b'.repeat(32)},next={...nextMetadata,status:'complete'};assert.throws(()=>writeReceiptCAS(fs,file,raw,metadata,next),/immutable ownership changed/);const output=writeReceiptCAS(fs,file,raw,metadata,next,nextMetadata);assert.equal(readFileSync(file,'utf8'),output);assert.throws(()=>writeReceiptCAS(fs,file,raw,metadata,next,nextMetadata),/expected bytes changed/);assert.equal(readFileSync(file,'utf8'),output);}));
test('ownership focal path replacement after descriptor pinning preserves new foreign file',()=>receipt(({dir,file,raw})=>{const foreign=path.join(dir,'foreign'),bytes='foreign replacement';writeFileSync(foreign,bytes);let stats=0;const proxy=Object.create(fs);proxy.statSync=p=>{if(++stats===2)renameSync(foreign,file);return fs.statSync(p);};assert.throws(()=>writeReceiptCAS(proxy,file,raw,metadata,{...metadata,status:'complete'}),/replaced immediately/);assert.equal(readFileSync(file,'utf8'),bytes);}));
test('ownership focal late replacement during pinned write does not overwrite foreign path',()=>receipt(({dir,file,raw})=>{const foreign=path.join(dir,'foreign'),bytes='later foreign replacement';writeFileSync(foreign,bytes);const proxy=Object.create(fs);proxy.writeSync=(...args)=>{renameSync(foreign,file);return fs.writeSync(...args);};assert.throws(()=>writeReceiptCAS(proxy,file,raw,metadata,{...metadata,status:'complete'}),/changed during write/);assert.equal(readFileSync(file,'utf8'),bytes);}));
function target(){const doc={documentURI:'app://observed/Sandbox'},wc={id:12,getURL:()=> 'app://observed/webcontents'},win={id:1,webContents:wc},key='aigility-manager-profile-baseline:test',token='a'.repeat(32),globals={[key]:{token,documentRef:doc,windowRef:win,webContentsRef:wc}},expected={windowId:1,webContentsId:12,documentURL:doc.documentURI,webContentsURL:wc.getURL(),baselineKey:key,baselineToken:token},remote={getCurrentWindow:()=>win},app={appId:'d137282e82167d84',vault:{getName:()=> 'Sandbox',adapter:{getBasePath:()=> '/Users/eme/Obsidian/Sandbox'}},workspace:{containerEl:{ownerDocument:doc}}};return {doc,wc,win,globals,expected,remote,app};}
test('ownership focal native gate accepts only previously frozen window webContents and document references',()=>{const f=target();assert.equal(frozenNativeIdentity(f.app,f.globals,f.doc,f.remote,f.expected),true);assert.throws(()=>frozenNativeIdentity(f.app,f.globals,f.doc,f.remote,null),/Frozen native target identity required/);});
test('ownership focal new window with reused IDs URLs is refused rather than adopted',()=>{const f=target();const replacement={id:1,webContents:{...f.wc}};assert.throws(()=>frozenNativeIdentity(f.app,f.globals,f.doc,{getCurrentWindow:()=>replacement},f.expected),/references changed/);assert.equal(f.globals[f.expected.baselineKey].windowRef,f.win);});
test('ownership focal reloaded document with identical URL is refused',()=>{const f=target(),replacement={documentURI:f.doc.documentURI};f.app.workspace.containerEl.ownerDocument=replacement;assert.throws(()=>frozenNativeIdentity(f.app,f.globals,replacement,f.remote,f.expected),/references changed/);});
test('ownership focal changes in webContents ID URL document URL or baseline token are refused',()=>{for(const change of [f=>f.wc.id++,f=>f.wc.getURL=()=> 'other',f=>f.doc.documentURI='other',f=>f.globals[f.expected.baselineKey].token='b'.repeat(32)]){const f=target();change(f);assert.throws(()=>frozenNativeIdentity(f.app,f.globals,f.doc,f.remote,f.expected),/changed/);}});
