import assert from 'node:assert/strict';
import {readFile,writeFile,mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {build} from 'esbuild';
import {pathToFileURL} from 'node:url';
import {ROOT,hash} from '../scripts/sandbox-community.mjs';
import {applyPatches,repairBody,getAt} from './redaction-recovery.check.mjs';
const incident=JSON.parse(await readFile(path.join(ROOT,'evidence/redaction-incident.json'),'utf8'));
const recovery=JSON.parse(await readFile(path.join(ROOT,'evidence/redaction-recovery.json'),'utf8'));
const proposal=JSON.parse(await readFile(path.join(ROOT,recovery.proposal),'utf8'));
const oldEntry=path.join(ROOT,incident.backupPath,'main.js'),oldMain=await readFile(oldEntry);
assert.equal(hash(oldMain),'17475c03f3bd161cdd1ad0a267ea600b7b5462fd317244c26a9ad33bcda35ada','Must use EXACT installed old binary');
const corrupt=JSON.parse(await readFile(path.join(ROOT,incident.backupPath,'data.json'),'utf8'));
assert.equal(hash(await readFile(path.join(ROOT,incident.backupPath,'data.json'))),proposal.expectedStateHash);
const intended=applyPatches(corrupt,proposal.patches);
const storage=new Map();globalThis.localStorage={getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k)};
globalThis.__notices=[];
const integration=await readFile(path.join(ROOT,'tests/integration.test.mjs'),'utf8');
const stubMatch=integration.match(/const STUB = (`[\s\S]*?`);/);assert(stubMatch,'Native source test stub not found');
const stub=new Function('return '+stubMatch[1])();
const hostSource=integration.slice(integration.indexOf('function makeState('),integration.indexOf('async function start(host)'));
const {makeHost}=new Function('storage',hostSource+'return {makeHost};')(storage);
const host=makeHost({layoutReady:true,initial:intended});host.app.appId='old-persist-proof';
host.app.plugins.manifests['enso-secret-placeholders']={id:'enso-secret-placeholders',name:'Secret Placeholders (ENSO)',version:'0.7.2-enso.1'};
host.app.plugins.enabledPlugins.add('enso-secret-placeholders');
host.app.plugins.plugins['enso-secret-placeholders']={_loaded:true};
const dir=await mkdtemp(path.join(os.tmpdir(),'aigility-old-persist-'));let plugin;
try{
 const stubPath=path.join(dir,'obsidian.mjs');await writeFile(stubPath,stub);
 const bundlePath=path.join(dir,'old.mjs');
 await build({absWorkingDir:ROOT,entryPoints:[oldEntry],bundle:true,format:'esm',platform:'node',target:'node22',alias:{obsidian:stubPath},outfile:bundlePath});
 const mod=await import(pathToFileURL(bundlePath).href),PluginClass=typeof mod.default==='function'?mod.default:mod.default.default;
 assert.equal(typeof PluginClass,'function');
 plugin=new PluginClass(host.app,host.manifest);await plugin.onload();
 const statePath=host.manifest.dir+'/data.json';
 let persisted=JSON.parse(host.files.get(statePath));
 // Establishes this binary actually recreates the original bug, rather than testing new code.
 for(const p of proposal.patches)assert.equal(getAt(persisted,p.path),'[redacted]','Old onload must reproduce damaged identity '+p.path.join('.'));
 assert.equal(typeof plugin.runtime.state.toJSON,'function','Old loaded state has the redactor attached');
 const F=Object.getPrototypeOf(async function(){}).constructor,job={};
 await new F('rt','__deploymentJob','let value;'+repairBody(proposal.patches,Date.now()+10000)+'return value;')(plugin.runtime,job);
 assert.equal(job.repairApplied,true);
 assert.equal(Object.hasOwn(plugin.runtime.state,'toJSON'),false,'OLD tx.refresh returns plain parsed State');
 await plugin.runtime.enqueue('old-protection-proof',async tx=>{const s=await tx.refresh();s.protected.push('community:own-proof');await tx.save();});
 plugin.runtime.pause('old-pause-proof');
 persisted=JSON.parse(host.files.get(statePath));
 for(const p of proposal.patches)assert.deepEqual(getAt(persisted,p.path),p.after,'Old subsequent persist re-corrupted repaired identity');
 assert.equal(plugin.runtime.list().find(x=>x.ref.id==='enso-secret-placeholders').desired,true);
 const writesBeforeUnload=host.writes.length;plugin.onunload();
 assert.equal(host.writes.length,writesBeforeUnload,'OLD unload does not reserialize State');
 persisted=JSON.parse(host.files.get(statePath));
 for(const p of proposal.patches)assert.deepEqual(getAt(persisted,p.path),p.after);
 const receipt={status:'passed-offline-old-binary',at:new Date().toISOString(),binarySha256:hash(oldMain),version:'0.1.0',patchCount:proposal.patches.length,oldOnloadBugReproduced:true,oldQueuedRefreshRemovesRedactor:true,subsequentProtectionSavePreservesRepair:true,pauseDoesNotRewriteState:true,unloadDoesNotRewriteState:true,targetDesiredTruePreserved:true,nativeHostMutations:false};
 await writeFile(path.join(ROOT,'evidence/old-runtime-persist.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt));
}finally{plugin?.onunload();await rm(dir,{recursive:true,force:true});}
